-- Create user_reports table
CREATE TABLE IF NOT EXISTS public.user_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    reporter_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    reported_id uuid NOT NULL REFERENCES public.user_profiles(id) ON DELETE CASCADE,
    reason text NOT NULL,
    details text,
    status text NOT NULL DEFAULT 'pending',
    CONSTRAINT user_reports_no_self_report CHECK (reporter_id <> reported_id)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_reports_reporter_id ON public.user_reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_reported_id ON public.user_reports(reported_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_status ON public.user_reports(status);

-- Prevent spamming duplicate pending reports against the same user
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_reports_pending_unique 
    ON public.user_reports (reporter_id, reported_id) 
    WHERE status = 'pending';

-- Enable Row Level Security
ALTER TABLE public.user_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_reports FORCE ROW LEVEL SECURITY;

-- Grants
GRANT ALL ON TABLE public.user_reports TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.user_reports_id_seq TO anon, authenticated, service_role;

-- Policies:
-- 1. Reporters can view their own submitted reports
CREATE POLICY own_can_read ON public.user_reports
    FOR SELECT
    TO authenticated
    USING (auth.uid() = reporter_id);

-- 2. Authenticated users can insert reports where reporter_id is themselves and status is pending
CREATE POLICY own_can_insert ON public.user_reports
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = reporter_id AND (status IS NULL OR status = 'pending'));

-- 3. Admins can view all reports
CREATE POLICY admin_can_read ON public.user_reports
    FOR SELECT
    TO authenticated
    USING (is_user_admin(auth.uid()));

-- 4. Admins can update reports (e.g. change status)
CREATE POLICY admin_can_update ON public.user_reports
    FOR UPDATE
    TO authenticated
    USING (is_user_admin(auth.uid()))
    WITH CHECK (is_user_admin(auth.uid()));

-- 5. Admins can delete reports
CREATE POLICY admin_can_delete ON public.user_reports
    FOR DELETE
    TO authenticated
    USING (is_user_admin(auth.uid()));
